---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  namespace: observability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-python-app
  template:
    metadata:
      labels:
        app: demo-python-app
    spec:
      containers:
        - name: app
          image: demo-python-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-python-app
  namespace: observability
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
  selector:
    app: demo-python-app